"""Bundles the generic `mis-mcp-runtime` package inside every generated
plugin (deployment Pattern A from the plan's open items - the default).

forge_core never *imports* mis_mcp_runtime (see that package's own
docstrings for why); it only locates it on disk via `importlib.util.find_spec`
and copies the source tree plus a small stdlib-only entry-point script and a
requirements.txt derived from its own pyproject.toml. If the runtime package
isn't installed in the current environment, bundling is skipped with a
warning rather than failing the whole generation run - the config/*.json
files are still written, and the plugin can point at a shared remote
runtime instead (Pattern B).
"""

from __future__ import annotations

import importlib.util
import shutil
import tomllib
from pathlib import Path

RUNTIME_PACKAGE_NAME = "mis_mcp_runtime"
RUNTIME_ENTRY_POINT = "run_server.py"

_ENTRY_POINT_TEMPLATE = '''"""Bundled entry point - do not edit by hand, regenerated by forge_core.

Runs the generic mis-mcp-runtime server against this plugin's config/data,
using only the vendored source tree next to this file plus whatever
dependencies were installed from requirements.txt.
"""
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))

from mis_mcp_runtime.server import main  # noqa: E402

if __name__ == "__main__":
    main()
'''


def locate_runtime_source() -> Path | None:
    """The directory containing the installed `mis_mcp_runtime` package, or
    None if it isn't installed in the current environment."""
    spec = importlib.util.find_spec(RUNTIME_PACKAGE_NAME)
    if spec is None or spec.origin is None:
        return None
    return Path(spec.origin).parent


def _runtime_requirements(runtime_source: Path) -> list[str]:
    pyproject_path = runtime_source.parent.parent / "pyproject.toml"
    if not pyproject_path.is_file():
        return []
    data = tomllib.loads(pyproject_path.read_text(encoding="utf-8"))
    deps: list[str] = data.get("project", {}).get("dependencies", [])
    return deps


def bundle_runtime(plugin_dir: Path, mcp_server_dirname: str = "mcp_server") -> bool:
    """Copy the installed mis-mcp-runtime source into
    `<plugin_dir>/<mcp_server_dirname>/`. Returns True if bundled, False if
    the runtime package could not be located (caller should warn)."""
    runtime_source = locate_runtime_source()
    if runtime_source is None:
        return False

    target_dir = plugin_dir / mcp_server_dirname
    target_dir.mkdir(parents=True, exist_ok=True)
    shutil.copytree(runtime_source, target_dir / RUNTIME_PACKAGE_NAME, dirs_exist_ok=True)

    (target_dir / RUNTIME_ENTRY_POINT).write_text(_ENTRY_POINT_TEMPLATE, encoding="utf-8")

    requirements = _runtime_requirements(runtime_source)
    (target_dir / "requirements.txt").write_text("\n".join(requirements) + "\n", encoding="utf-8")
    return True
