"""Stage 7 - PACKAGE. Turns already-generated, already-validated pipeline
output into a real, installable Claude Code plugin directory: every
constraint in plan §4 is enforced by construction (via the plugin_spec
models) rather than by string formatting.

Two-step API: `build_plugin_spec()` produces an in-memory `PluginSpec`
(pure, easy to unit test), `write_plugin()` serializes it to disk as
BOM-less UTF-8 and bundles the generic MCP runtime alongside it.
"""

from __future__ import annotations

import json
from pathlib import Path

from forge_core.generation import MCP_SERVER_NAME, GeneratedPlugin
from forge_core.models.bindings import SchemaBindings
from forge_core.models.datasource import DataSource
from forge_core.models.industry_pack import IndustryPack
from forge_core.models.kpi import KpiDefsFile
from forge_core.models.plugin_spec import (
    Author,
    GeneratedFile,
    McpConfig,
    McpStdioServer,
    PluginManifest,
    PluginSpec,
)
from forge_core.models.schema_profile import SchemaProfile
from forge_core.packaging.mcp_bundle import bundle_runtime
from forge_core.packaging.redaction import write_redacted_data_files
from forge_core.packaging.versioning import INITIAL_VERSION
from forge_core.validation.frontmatter import render_frontmatter

DEFAULT_AUTHOR = Author(name="MIS Plugin Forge")


def plugin_name_for(pack: IndustryPack) -> str:
    return f"{pack.slug}-mis-plugin"


def _config_files(
    profile: SchemaProfile, bindings: SchemaBindings, kpi_defs: KpiDefsFile
) -> list[GeneratedFile]:
    source = profile.source
    data_source_json = {
        "kind": source.kind.value,
        "connection": {
            "duckdb_attach_sql": source.connection.duckdb_attach_sql,
            "read_only": source.connection.read_only,
        },
        "tables": [
            {"name": t.name, "physical_ref": t.physical_ref, "columns": [c.name for c in t.columns]}
            for t in source.tables
        ],
    }
    schema_summary_json = {
        "pack_slug": kpi_defs.pack_slug,
        "tables": [{"name": t.name, "columns": [c.name for c in t.columns]} for t in source.tables],
    }

    return [
        GeneratedFile(
            relative_path="config/data_source.json",
            content=json.dumps(data_source_json, indent=2),
            is_json=True,
        ),
        GeneratedFile(
            relative_path="config/schema_bindings.json",
            content=bindings.model_dump_json(indent=2),
            is_json=True,
        ),
        GeneratedFile(
            relative_path="config/kpi_defs.json", content=kpi_defs.model_dump_json(indent=2), is_json=True
        ),
        GeneratedFile(
            relative_path="config/schema_summary.json",
            content=json.dumps(schema_summary_json, indent=2),
            is_json=True,
        ),
    ]


def _mcp_config() -> McpConfig:
    return McpConfig(
        mcpServers={
            MCP_SERVER_NAME: McpStdioServer(
                command="python",
                args=["${CLAUDE_PLUGIN_ROOT}/mcp_server/run_server.py"],
                env={
                    "MIS_MCP_CONFIG_DIR": "${CLAUDE_PLUGIN_ROOT}/config",
                    "MIS_MCP_DATA_DIR": "${CLAUDE_PLUGIN_ROOT}/data",
                },
            )
        }
    )


def _readme(pack: IndustryPack, kpi_defs: KpiDefsFile, plugin_name: str, version: str) -> str:
    kpi_lines = "\n".join(f"- `{k.id}` - {k.label}" for k in kpi_defs.kpis)
    return (
        f"# {plugin_name}\n\n"
        f"Version {version}. Generated by MIS Plugin Forge for the **{pack.name}** industry pack.\n\n"
        "## Setup\n\n"
        "1. Install the bundled MCP server's dependencies: "
        "`pip install -r mcp_server/requirements.txt`\n"
        "2. Install this plugin directory in Claude Code (`/plugin install <path>` or via a "
        "marketplace).\n\n"
        "## Available KPIs\n\n"
        f"{kpi_lines}\n"
    )


def build_plugin_spec(
    pack: IndustryPack,
    profile: SchemaProfile,
    bindings: SchemaBindings,
    kpi_defs: KpiDefsFile,
    generated: GeneratedPlugin,
    *,
    plugin_name: str | None = None,
    version: str = INITIAL_VERSION,
    author: Author | None = None,
) -> PluginSpec:
    """Build the complete in-memory plugin. Every path here is a
    conventional directory (`skills/`, `agents/`, `commands/`,
    `hooks/hooks.json`, `.mcp.json`) so the manifest relies on Claude Code's
    auto-discovery and never needs to declare explicit component paths."""
    name = plugin_name or plugin_name_for(pack)

    manifest = PluginManifest(
        name=name,
        displayName=f"{pack.name} Analyst",
        version=version,
        description=pack.description,
        author=author or DEFAULT_AUTHOR,
        keywords=[pack.slug, "mis-plugin-forge"],
    )

    files: list[GeneratedFile] = [
        GeneratedFile(
            relative_path=f"skills/{generated.skill_name}/SKILL.md",
            content=render_frontmatter(
                generated.skill_frontmatter.to_frontmatter_dict(), generated.skill_body
            ),
        ),
        GeneratedFile(
            relative_path=f"agents/{generated.agent_name}.md",
            content=render_frontmatter(
                generated.agent_frontmatter.to_frontmatter_dict(), generated.agent_body
            ),
        ),
        GeneratedFile(relative_path="artifacts/dashboard.html", content=generated.dashboard_html),
    ]
    for command in generated.commands:
        files.append(
            GeneratedFile(
                relative_path=f"commands/{command.name}.md",
                content=render_frontmatter(command.frontmatter.to_frontmatter_dict(), command.body),
            )
        )
    files.extend(_config_files(profile, bindings, kpi_defs))

    return PluginSpec(
        manifest=manifest,
        mcp_config=_mcp_config(),
        hooks=generated.hooks,
        files=files,
        readme=_readme(pack, kpi_defs, name, version),
    )


def write_plugin(
    spec: PluginSpec,
    output_dir: Path,
    *,
    source: DataSource | None = None,
    profile: SchemaProfile | None = None,
    pack: IndustryPack | None = None,
    bundle_mcp_runtime: bool = True,
) -> Path:
    """Serialize a `PluginSpec` to disk as BOM-less UTF-8, write the source
    data it references (redacted per `pack`'s guardrails - see
    forge_core.packaging.redaction), and bundle the generic MCP runtime next
    to it. Returns `output_dir`."""
    output_dir.mkdir(parents=True, exist_ok=True)

    manifest_dir = output_dir / ".claude-plugin"
    manifest_dir.mkdir(exist_ok=True)
    _write_text(manifest_dir / "plugin.json", json.dumps(spec.manifest.to_json_dict(), indent=2))

    if spec.mcp_config is not None:
        _write_text(output_dir / ".mcp.json", json.dumps(spec.mcp_config.to_json_dict(), indent=2))

    if spec.hooks is not None:
        hooks_dir = output_dir / "hooks"
        hooks_dir.mkdir(exist_ok=True)
        _write_text(hooks_dir / "hooks.json", json.dumps(spec.hooks.to_json_dict(), indent=2))

    for f in spec.files:
        target = output_dir / f.relative_path
        target.parent.mkdir(parents=True, exist_ok=True)
        _write_text(target, f.content)

    if spec.readme:
        _write_text(output_dir / "README.md", spec.readme)

    if source is not None:
        if profile is None or pack is None:
            raise ValueError(
                "write_plugin(source=...) requires profile= and pack= too, so denied columns "
                "(PII, or any role category the pack's guardrails deny) can be redacted before "
                "the data ships inside the plugin - see forge_core.packaging.redaction."
            )
        write_redacted_data_files(source, profile, pack, output_dir)

    if bundle_mcp_runtime:
        bundle_runtime(output_dir)

    return output_dir


def _write_text(path: Path, content: str) -> None:
    """UTF-8, no BOM, exactly the content given plus a single trailing
    newline - the exact thing the plugin_spec validation check verifies."""
    text = content if content.endswith("\n") else content + "\n"
    path.write_text(text, encoding="utf-8", newline="\n")
